import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/WebComponent/NavBar.1";
import Footer from "@/WebComponent/Footer";
import Bar from "@/WebComponent/Bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bakas",
  description: "Generated by Bakas Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div>
        <Bar />
        <Navbar />
        <body className={inter.className}>{children}</body>
        <Footer />
      </div>
    </html>
  );
}
